CREATE TABLE COUNTRY (
    CODE VARCHAR(3),         
    NAME VARCHAR(44),        
    CONTINENT VARCHAR(13),  
    REGION VARCHAR(25),      
    SURFACEAREA FLOAT,
    INDEPYEAR VARCHAR(5),
    POPULATION INT,
    LIFEEXPECTANCY VARCHAR(4),
    GNP FLOAT,
    GNPOLD VARCHAR(9),
    LOCALNAME VARCHAR(44),
    GOVERNMENTFORM VARCHAR(44),
    HEADOFSTATE VARCHAR(32),
    CAPITAL VARCHAR(4),
    CODE2 VARCHAR(2)
);

CREATE TABLE CITY (
    ID INT,                  
    NAME VARCHAR(17),        
    COUNTRYCODE VARCHAR(3),   
    DISTRICT VARCHAR(20),
    POPULATION INT
);

INSERT INTO COUNTRY (CODE, NAME, CONTINENT, REGION, POPULATION)
VALUES
('NGA', 'Nigeria', 'Africa', 'Western Africa', 200000000),
('EGY', 'Egypt', 'Africa', 'Northern Africa', 100000000),
('IND', 'India', 'Asia', 'Southern Asia', 1380000000);

INSERT INTO CITY (ID, NAME, COUNTRYCODE, DISTRICT, POPULATION)
VALUES
(1, 'Lagos', 'NGA', 'Lagos', 9000000),
(2, 'Abuja', 'NGA', 'Abuja', 3000000),
(3, 'Cairo', 'EGY', 'Cairo', 9500000),
(4, 'Mumbai', 'IND', 'Maharashtra', 20000000);

SELECT CITY.NAME
FROM CITY
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.CONTINENT = 'Africa';
