CREATE DATABASE CityDB;
USE CityDB;

CREATE TABLE CITY (
    ID INT,
    NAME VARCHAR(17),
    COUNTRYCODE VARCHAR(3),
    DISTRICT VARCHAR(20),
    POPULATION INT
);

INSERT INTO CITY VALUES (1, 'Mumbai', 'IND', 'Maharashtra', 20000000);
INSERT INTO CITY VALUES (2, 'Delhi', 'IND', 'Delhi', 18000000);
INSERT INTO CITY VALUES (3, 'Chennai', 'IND', 'Tamil Nadu', 10000000);
INSERT INTO CITY VALUES (1661, 'SampleCity', 'XYZ', 'SampleDistrict', 123456);

SELECT * FROM CITY;

SELECT * FROM city WHERE ID = 1661;






