CREATE DATABASE IF NOT EXISTS StationDB;
USE StationDB;


CREATE TABLE IF NOT EXISTS STATION (
    ID INT PRIMARY KEY,
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    LAT_N FLOAT,
    LONG_W FLOAT
);


INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES
(1, 'Amo', 'MP', 22.67, 75.89),
(2, 'Marine On Saint Croix', 'MN', 45.2, 92.77),
(3, 'Delhi', 'DL', 28.61, 77.23),
(4, 'Goa', 'GA', 15.49, 73.83),
(5, 'LosAngeles', 'CA', 34.05, 118.24),
(6, 'Ahmedabad', 'GJ', 23.03, 72.57);

SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY), CITY LIMIT 1;

SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1;
