CREATE DATABASE TestDB;
USE TestDB;

CREATE TABLE STATION (
    ID INT,
    CITY VARCHAR(21),
    STATE VARCHAR(2),
    LAT_N FLOAT,
    LONG_W FLOAT
);


INSERT INTO STATION VALUES (1, 'Los Angeles', 'CA', 34.05, -118.25);
INSERT INTO STATION VALUES (2, 'New York', 'NY', 40.71, -74.01);
INSERT INTO STATION VALUES (3, 'Chicago', 'IL', 41.88, -87.62);

SELECT CITY, STATE
FROM STATION;

